### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by noberg1** [squareweave/wagtailcolumnblocks#3]
I somehow can't get this to work with my wagtail-project. How would you say is the proper way of installing this? I've used 
`pip3 install git+https://github.com/squareweave/wagtailcolumnblocks.git`
without success. I have also tried using the setup.py but that does not work either. Sorry for the dumb question.

Thank you.

**Comment by stefan-squareweave** [comment]
@noberg1 I've updated the README with some instructions. Your issues would likely have centred around the package using the SASS compiler, and perhaps not including it in INSTALLED_APPs. I've removed the SASS dependency, and you should find everything else you need in the README now.

**Comment by stefan-squareweave** [comment]
You can use the pip line you included to install the package now, but I'll try and update the Pypi repository with the latest version now also.

**Comment by noberg1** [comment]
Thanks for the fast reply. I tried uninstall it and reinstall it again and add it to the INSTALLED_APPS. When i migrate i get the following error;
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/nobeg/Documents/cms/home/models.py", line 13, in <module>
    class ColumnBlocks(blocks.StreamBlock):
  File "/Users/nobeg/Documents/cms/home/models.py", line 16, in ColumnBlocks
    column_1_1 = ColumnsBlock(
NameError: name 'ColumnsBlock' is not defined`

**Comment by stefan-squareweave** [comment]
It sounds like you're missing the `from wagtailcolumnblocks.blocks import ColumnsBlock` line in your home/models.py file ?

**Comment by noberg1** [comment]
Yes, thats it. Thank you!!
